// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bagian.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	bagian.proto

It has these top-level messages:
	AddBagianReq
	ReadBagian
	ReadBagianAktifResp
	ReadBagianResp
	UpdateBagianReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddBagianReq struct {
	IDBagian   string `protobuf:"bytes,1,opt,name=IDBagian" json:"IDBagian,omitempty"`
	NamaBagian string `protobuf:"bytes,2,opt,name=NamaBagian" json:"NamaBagian,omitempty"`
	Deskripsi  string `protobuf:"bytes,3,opt,name=Deskripsi" json:"Deskripsi,omitempty"`
	Status     int32  `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	CreatedBy  string `protobuf:"bytes,5,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn  string `protobuf:"bytes,6,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdatedBy  string `protobuf:"bytes,7,opt,name=UpdatedBy" json:"UpdatedBy,omitempty"`
	UpdateOn   string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
}

func (m *AddBagianReq) Reset()                    { *m = AddBagianReq{} }
func (m *AddBagianReq) String() string            { return proto.CompactTextString(m) }
func (*AddBagianReq) ProtoMessage()               {}
func (*AddBagianReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddBagianReq) GetIDBagian() string {
	if m != nil {
		return m.IDBagian
	}
	return ""
}

func (m *AddBagianReq) GetNamaBagian() string {
	if m != nil {
		return m.NamaBagian
	}
	return ""
}

func (m *AddBagianReq) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *AddBagianReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddBagianReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AddBagianReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *AddBagianReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *AddBagianReq) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

type ReadBagian struct {
	IDBagian   string `protobuf:"bytes,1,opt,name=IDBagian" json:"IDBagian,omitempty"`
	NamaBagian string `protobuf:"bytes,2,opt,name=NamaBagian" json:"NamaBagian,omitempty"`
	Deskripsi  string `protobuf:"bytes,3,opt,name=Deskripsi" json:"Deskripsi,omitempty"`
	Status     int32  `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	CreatedBy  string `protobuf:"bytes,5,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn  string `protobuf:"bytes,6,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdatedBy  string `protobuf:"bytes,7,opt,name=UpdatedBy" json:"UpdatedBy,omitempty"`
	UpdateOn   string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
}

func (m *ReadBagian) Reset()                    { *m = ReadBagian{} }
func (m *ReadBagian) String() string            { return proto.CompactTextString(m) }
func (*ReadBagian) ProtoMessage()               {}
func (*ReadBagian) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadBagian) GetIDBagian() string {
	if m != nil {
		return m.IDBagian
	}
	return ""
}

func (m *ReadBagian) GetNamaBagian() string {
	if m != nil {
		return m.NamaBagian
	}
	return ""
}

func (m *ReadBagian) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *ReadBagian) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadBagian) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ReadBagian) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *ReadBagian) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *ReadBagian) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

type ReadBagianAktifResp struct {
	AllAktif []*ReadBagian `protobuf:"bytes,1,rep,name=allAktif" json:"allAktif,omitempty"`
}

func (m *ReadBagianAktifResp) Reset()                    { *m = ReadBagianAktifResp{} }
func (m *ReadBagianAktifResp) String() string            { return proto.CompactTextString(m) }
func (*ReadBagianAktifResp) ProtoMessage()               {}
func (*ReadBagianAktifResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadBagianAktifResp) GetAllAktif() []*ReadBagian {
	if m != nil {
		return m.AllAktif
	}
	return nil
}

type ReadBagianResp struct {
	AllBagian []*ReadBagian `protobuf:"bytes,1,rep,name=allBagian" json:"allBagian,omitempty"`
}

func (m *ReadBagianResp) Reset()                    { *m = ReadBagianResp{} }
func (m *ReadBagianResp) String() string            { return proto.CompactTextString(m) }
func (*ReadBagianResp) ProtoMessage()               {}
func (*ReadBagianResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadBagianResp) GetAllBagian() []*ReadBagian {
	if m != nil {
		return m.AllBagian
	}
	return nil
}

type UpdateBagianReq struct {
	IDBagian   string `protobuf:"bytes,1,opt,name=IDBagian" json:"IDBagian,omitempty"`
	NamaBagian string `protobuf:"bytes,2,opt,name=NamaBagian" json:"NamaBagian,omitempty"`
	Deskripsi  string `protobuf:"bytes,3,opt,name=Deskripsi" json:"Deskripsi,omitempty"`
	Status     int32  `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	CreatedBy  string `protobuf:"bytes,5,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn  string `protobuf:"bytes,6,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdatedBy  string `protobuf:"bytes,7,opt,name=UpdatedBy" json:"UpdatedBy,omitempty"`
	UpdateOn   string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
}

func (m *UpdateBagianReq) Reset()                    { *m = UpdateBagianReq{} }
func (m *UpdateBagianReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateBagianReq) ProtoMessage()               {}
func (*UpdateBagianReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateBagianReq) GetIDBagian() string {
	if m != nil {
		return m.IDBagian
	}
	return ""
}

func (m *UpdateBagianReq) GetNamaBagian() string {
	if m != nil {
		return m.NamaBagian
	}
	return ""
}

func (m *UpdateBagianReq) GetDeskripsi() string {
	if m != nil {
		return m.Deskripsi
	}
	return ""
}

func (m *UpdateBagianReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateBagianReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *UpdateBagianReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *UpdateBagianReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *UpdateBagianReq) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func init() {
	proto.RegisterType((*AddBagianReq)(nil), "grpc.AddBagianReq")
	proto.RegisterType((*ReadBagian)(nil), "grpc.ReadBagian")
	proto.RegisterType((*ReadBagianAktifResp)(nil), "grpc.ReadBagianAktifResp")
	proto.RegisterType((*ReadBagianResp)(nil), "grpc.ReadBagianResp")
	proto.RegisterType((*UpdateBagianReq)(nil), "grpc.UpdateBagianReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for BagianService service

type BagianServiceClient interface {
	AddBagian(ctx context.Context, in *AddBagianReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadBagianAktif(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadBagianAktifResp, error)
	ReadBagian(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadBagianResp, error)
	UpdateBagian(ctx context.Context, in *UpdateBagianReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type bagianServiceClient struct {
	cc *grpc1.ClientConn
}

func NewBagianServiceClient(cc *grpc1.ClientConn) BagianServiceClient {
	return &bagianServiceClient{cc}
}

func (c *bagianServiceClient) AddBagian(ctx context.Context, in *AddBagianReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.BagianService/AddBagian", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bagianServiceClient) ReadBagianAktif(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadBagianAktifResp, error) {
	out := new(ReadBagianAktifResp)
	err := grpc1.Invoke(ctx, "/grpc.BagianService/ReadBagianAktif", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bagianServiceClient) ReadBagian(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadBagianResp, error) {
	out := new(ReadBagianResp)
	err := grpc1.Invoke(ctx, "/grpc.BagianService/ReadBagian", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bagianServiceClient) UpdateBagian(ctx context.Context, in *UpdateBagianReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.BagianService/UpdateBagian", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BagianService service

type BagianServiceServer interface {
	AddBagian(context.Context, *AddBagianReq) (*google_protobuf.Empty, error)
	ReadBagianAktif(context.Context, *google_protobuf.Empty) (*ReadBagianAktifResp, error)
	ReadBagian(context.Context, *google_protobuf.Empty) (*ReadBagianResp, error)
	UpdateBagian(context.Context, *UpdateBagianReq) (*google_protobuf.Empty, error)
}

func RegisterBagianServiceServer(s *grpc1.Server, srv BagianServiceServer) {
	s.RegisterService(&_BagianService_serviceDesc, srv)
}

func _BagianService_AddBagian_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBagianReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BagianServiceServer).AddBagian(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BagianService/AddBagian",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BagianServiceServer).AddBagian(ctx, req.(*AddBagianReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BagianService_ReadBagianAktif_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BagianServiceServer).ReadBagianAktif(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BagianService/ReadBagianAktif",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BagianServiceServer).ReadBagianAktif(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BagianService_ReadBagian_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BagianServiceServer).ReadBagian(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BagianService/ReadBagian",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BagianServiceServer).ReadBagian(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BagianService_UpdateBagian_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBagianReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BagianServiceServer).UpdateBagian(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BagianService/UpdateBagian",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BagianServiceServer).UpdateBagian(ctx, req.(*UpdateBagianReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BagianService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.BagianService",
	HandlerType: (*BagianServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddBagian",
			Handler:    _BagianService_AddBagian_Handler,
		},
		{
			MethodName: "ReadBagianAktif",
			Handler:    _BagianService_ReadBagianAktif_Handler,
		},
		{
			MethodName: "ReadBagian",
			Handler:    _BagianService_ReadBagian_Handler,
		},
		{
			MethodName: "UpdateBagian",
			Handler:    _BagianService_UpdateBagian_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "bagian.proto",
}

func init() { proto.RegisterFile("bagian.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x53, 0xdd, 0x4e, 0xc2, 0x30,
	0x18, 0xa5, 0xfc, 0xc9, 0x3e, 0x51, 0x4c, 0x55, 0x52, 0xa7, 0x31, 0x64, 0x57, 0x5c, 0x98, 0x92,
	0xe0, 0x95, 0x89, 0x89, 0xf2, 0xa3, 0x89, 0x37, 0x92, 0x8c, 0xf8, 0x00, 0x85, 0x95, 0x65, 0x61,
	0xb0, 0xb9, 0x0d, 0x13, 0x1e, 0xc3, 0x77, 0x35, 0x26, 0xde, 0x99, 0xb5, 0xa3, 0x1b, 0xe8, 0x9e,
	0x80, 0xcb, 0xef, 0x7c, 0xe7, 0x6c, 0x3d, 0x3d, 0x3d, 0x50, 0x9f, 0x30, 0xdb, 0x61, 0x4b, 0xea,
	0x07, 0x5e, 0xe4, 0xe1, 0xb2, 0x1d, 0xf8, 0x53, 0xfd, 0xd2, 0xf6, 0x3c, 0xdb, 0xe5, 0x1d, 0x81,
	0x4d, 0x56, 0xb3, 0x0e, 0x5f, 0xf8, 0xd1, 0x5a, 0x52, 0x8c, 0x6f, 0x04, 0xf5, 0x9e, 0x65, 0xf5,
	0x85, 0xcc, 0xe4, 0xef, 0x58, 0x87, 0xda, 0xcb, 0x50, 0x8e, 0x04, 0xb5, 0x50, 0x5b, 0x33, 0xd5,
	0x8c, 0xaf, 0x01, 0x5e, 0xd9, 0x82, 0x25, 0xdb, 0xa2, 0xd8, 0x66, 0x10, 0x7c, 0x05, 0xda, 0x90,
	0x87, 0xf3, 0xc0, 0xf1, 0x43, 0x87, 0x94, 0xc4, 0x3a, 0x05, 0x70, 0x13, 0xaa, 0xe3, 0x88, 0x45,
	0xab, 0x90, 0x94, 0x5b, 0xa8, 0x5d, 0x31, 0x93, 0x29, 0x56, 0x0d, 0x02, 0xce, 0x22, 0x6e, 0xf5,
	0xd7, 0xa4, 0x22, 0x55, 0x0a, 0xc8, 0x6c, 0x47, 0x4b, 0x52, 0xdd, 0xda, 0x8e, 0xc4, 0x1f, 0xdf,
	0x7c, 0x2b, 0xd1, 0x1e, 0xc8, 0xad, 0x02, 0x62, 0x2f, 0x72, 0x18, 0x2d, 0x49, 0x4d, 0x7a, 0xd9,
	0xcc, 0xc6, 0x17, 0x02, 0x30, 0x39, 0x4b, 0x9c, 0xef, 0x8d, 0xed, 0x01, 0x9c, 0xa6, 0xae, 0x7b,
	0xf3, 0xc8, 0x99, 0x99, 0x3c, 0xf4, 0xf1, 0x0d, 0xd4, 0x98, 0xeb, 0x8a, 0x99, 0xa0, 0x56, 0xa9,
	0x7d, 0xd8, 0x3d, 0xa1, 0xf1, 0xe3, 0xa1, 0x29, 0xd9, 0x54, 0x0c, 0xe3, 0x11, 0x8e, 0x33, 0x78,
	0xac, 0xa7, 0xa0, 0x31, 0xd7, 0x55, 0xf7, 0xf7, 0xff, 0x07, 0x52, 0x8a, 0xf1, 0x83, 0xa0, 0x21,
	0xcf, 0xb4, 0x77, 0x2f, 0xaf, 0xfb, 0x59, 0x84, 0x23, 0x79, 0xec, 0x31, 0x0f, 0x3e, 0x9c, 0x29,
	0xc7, 0x77, 0xa0, 0xa9, 0x0e, 0x62, 0x2c, 0xef, 0x2d, 0x5b, 0x4a, 0xbd, 0x49, 0x65, 0x87, 0xe9,
	0xa6, 0xc3, 0xf4, 0x29, 0xee, 0xb0, 0x51, 0xc0, 0xcf, 0xd0, 0xd8, 0xc9, 0x13, 0xe7, 0x90, 0xf5,
	0x8b, 0xdd, 0x40, 0x54, 0xfc, 0x46, 0x01, 0xdf, 0x6f, 0xb5, 0x21, 0xef, 0x13, 0x67, 0x7f, 0x32,
	0x95, 0xea, 0x07, 0xa8, 0x67, 0xd3, 0xc4, 0xe7, 0x92, 0xb7, 0x93, 0x70, 0xbe, 0x8d, 0x49, 0x55,
	0x20, 0xb7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x45, 0xc3, 0xae, 0xc0, 0x04, 0x00, 0x00,
}
